<h1 align="center"> Filoger Summer School 2022<h1>
<h1 align="center"> Data Science & Machine Learning (Dr.Zabihin) <h1>

# 07- Regularization (Ridge - LASSO - ElasticNet)




### Step1: Import all Necessary Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### Step2: Import the Data

In [2]:
df= pd.read_csv('Advertising.csv')

### Step3: Data Overview

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

**Note: You can do more overview by yourself** 

### Step4: EDA

**Note: Do it by yourself**

### Step5: Determine the Features & Target Variable (Lable)

In [3]:
X= df.drop('sales', axis=1)
y=df['sales']

### Step6: Preprocessing (Polynomial Conversion)

In [4]:
from sklearn.preprocessing import PolynomialFeatures

In [5]:
polynomial_converter= PolynomialFeatures(degree=3, include_bias=False)

In [6]:
poly_features= polynomial_converter.fit_transform(X)

In [7]:
poly_features.shape

(200, 19)

### Step7: Split the Data to Train & Test

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

### Step8: Scaling the Data

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler= StandardScaler()

In [12]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [13]:
X_train= scaler.transform(X_train)
X_test= scaler.transform(X_test)

### Step9: Regularization

### 1- Ridge Regression

In [24]:
#Train the Model
from sklearn.linear_model import Ridge

In [25]:
ridge_model= Ridge(alpha=10)

In [26]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [27]:
#predict Test Data
y_pred= ridge_model.predict(X_test)

In [28]:
#Evaluating the Model
from sklearn.metrics import mean_absolute_error, mean_squared_error

MAE= mean_absolute_error(y_test, y_pred)
MSE= mean_squared_error(y_test, y_pred)
RMSE= np.sqrt(MSE)

In [20]:
pd.DataFrame([MAE, MSE, RMSE], index=['MAE', 'MSE', 'RMSE'], columns=['metrics'])

metrics
MAE   0.577440
MSE   0.800378
RMSE  0.894639

### Ridge Regression (Coosing an alpha value with Cross-Validation)

In [15]:
#Train the Model
from sklearn.linear_model import RidgeCV

In [16]:
ridge_cv_model=RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [17]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=None, fit_intercept=True,
    gcv_mode=None, normalize=False, scoring='neg_mean_absolute_error',
    store_cv_values=False)

In [18]:
ridge_cv_model.alpha_

0.1

In [19]:
#Predicting Test Data
y_pred_ridge= ridge_cv_model.predict(X_test)

In [29]:
MAE_ridge= mean_absolute_error(y_test, y_pred_ridge)
MSE_ridge= mean_squared_error(y_test, y_pred_ridge)
RMSE_ridge= np.sqrt(MSE_ridge)

In [30]:
pd.DataFrame([MAE_ridge, MSE_ridge, RMSE_ridge], index=['MAE', 'MSE', 'RMSE'], columns=['Ridge Metrics'])

Ridge Metrics
MAE        0.427377
MSE        0.382013
RMSE       0.618072

In [38]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

### 2- Lasso Regression

In [32]:
from sklearn.linear_model import LassoCV

In [34]:
lasso_cv_model= LassoCV(eps=0.01, n_alphas=100, cv=5)

In [35]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(alphas=None, copy_X=True, cv=5, eps=0.01, fit_intercept=True,
    max_iter=1000, n_alphas=100, n_jobs=None, normalize=False,
    positive=False, precompute='auto', random_state=None,
    selection='cyclic', tol=0.0001, verbose=False)

In [36]:
lasso_cv_model.alpha_

0.049430709092258295

In [37]:
y_pred_lasso= lasso_cv_model.predict(X_test)

In [38]:
MAE_Lasso= mean_absolute_error(y_test, y_pred_lasso)
MSE_Lasso= mean_squared_error(y_test, y_pred_lasso)
RMSE_Lasso= np.sqrt(MSE_Lasso)

In [78]:
pd.DataFrame([MAE_Lasso, MSE_Lasso, RMSE_Lasso], index=['MAE', 'MSE', 'RMSE'], columns=['Lasso Metrics'])

Lasso Metrics
MAE        0.515979
MSE        0.579949
RMSE       0.761544

In [39]:
lasso_cv_model.coef_

array([ 2.35600233,  0.21183181,  0.        , -0.        ,  3.78675114,
       -0.        ,  0.        ,  0.0624318 ,  0.        , -1.01152151,
       -0.        , -0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

### 3- Elastic Net

In [40]:
from sklearn.linear_model import ElasticNetCV

In [41]:
elastic_model= ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1],cv=5, max_iter=100000)

In [42]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(alphas=None, copy_X=True, cv=5, eps=0.001, fit_intercept=True,
       l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=100000,
       n_alphas=100, n_jobs=None, normalize=False, positive=False,
       precompute='auto', random_state=None, selection='cyclic',
       tol=0.0001, verbose=0)

In [43]:
elastic_model.l1_ratio_

1.0

In [84]:
y_pred_elastic=elastic_model.predict(X_test)

In [85]:
MAE_Elastic= mean_absolute_error(y_test, y_pred_elastic)
MSE_Elastic= mean_squared_error(y_test, y_pred_elastic)
RMSE_Elastic= np.sqrt(MSE_Elastic)

In [86]:
pd.DataFrame([MAE_Elastic, MSE_Elastic, RMSE_Elastic], index=['MAE', 'MSE', 'RMSE'], columns=['Elastic Metrics'])

Elastic Metrics
MAE          0.433503
MSE          0.367617
RMSE         0.606314

In [87]:
elastic_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])